####### Entities #######
LABEL_HOUSE = "house"
LABEL_AREA = "area"
LABEL_AUTHOR = "author"
LABEL_BATH_ROOM = "bath_room"
LABEL_BED_ROOM = "bed_room"
LABEL_CITY = "city"
LABEL_DIRECTION = "direction"
LABEL_DISTRICT = "district"
LABEL_EMAIL = "email"
LABEL_FLOOR = "floor"
LABEL_FRONT_LENGTH = "front_length"
LABEL_HOUSE_NUMBER = "house_number"
LABEL_LEGAL = "legal"
LABEL_LIVING_ROOM = "living_room"
LABEL_PHONE = "phone"
LABEL_POSITION = "position"
LABEL_PRICE = "price"
LABEL_PROJECT_NAME = "project_name"
LABEL_REAL_ESTATE_SUB_TYPE = "real_estate_sub_type"
LABEL_REAL_ESTATE_TYPE = "real_estate_type"
LABEL_ROAD_WIDTH = "road_width"
LABEL_STREET = "street"
LABEL_SURROUNDING = "surrounding"
LABEL_TRANSACTION = "transaction"
LABEL_USAGE = "usage"
LABEL_WARD = "ward"
LABEL_FLOOR_GAC = "floor_gac"
LABEL_FLOOR_TRET = "floor_tret"
LABEL_FLOOR_LUNG = "floor_lung"
LABEL_FLOOR_HAM = "floor_ham"
LABEL_FLOOR_BAN_CONG = "floor_ban_cong"
LABEL_FLOOR_SAN_THUONG = "floor_san_thuong"

MAJOR_ENTITIES = [LABEL_AREA, LABEL_PRICE, LABEL_USAGE, LABEL_DISTRICT]

MINOR_ENTITIES = [LABEL_AUTHOR, LABEL_BATH_ROOM, LABEL_BED_ROOM, LABEL_CITY, LABEL_DIRECTION, LABEL_EMAIL, LABEL_FLOOR, LABEL_FRONT_LENGTH, LABEL_HOUSE_NUMBER, \
                LABEL_LEGAL, LABEL_LIVING_ROOM, LABEL_PHONE, LABEL_POSITION, LABEL_PROJECT_NAME, LABEL_REAL_ESTATE_SUB_TYPE, LABEL_REAL_ESTATE_TYPE, LABEL_ROAD_WIDTH, \
                LABEL_STREET, LABEL_SURROUNDING, LABEL_TRANSACTION, LABEL_WARD,
                LABEL_FLOOR_GAC, LABEL_FLOOR_TRET, LABEL_FLOOR_LUNG, LABEL_FLOOR_HAM, LABEL_FLOOR_BAN_CONG, LABEL_FLOOR_SAN_THUONG]

####### Intents #######
# prediction of the model
INTENT_REAL_ESTATE = "real_estate"
INTENT_PRICE = "price"
INTENT_AREA = "area"
INTENT_USAGE = "usage"
INTENT_LOCATION = "location"
INTENT_DISTRICT = "district"
INTENT_HELLO = "hello"

# self-defined
INTENT_NOT_UNDERSTAND = 'not_understand'
INTENT_YES = "yes"
INTENT_NO = "no"

MAJOR_INTENTS = [
    INTENT_REAL_ESTATE, INTENT_PRICE, INTENT_AREA, INTENT_LOCATION,
    INTENT_DISTRICT
]
FAILURE_THRESHOLD = 2